name = "T4ATensorTrain"
uuid = "ec6ec972-96ae-4a21-b859-3911b77e305f"
authors = ["tensor4all contributors"]
version = "0.2.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
T4AMatrixCI = "c72b89c1-c391-41a7-b711-dfcca653bb47"

[weakdeps]
ITensors = "9136182c-28ba-11e9-034c-db9fb085ebd5"
ITensorMPS = "0d1a4710-d33b-49a5-8f18-73bdf49b47e2"
T4AITensorCompat = "864b39ca-388c-4f43-a593-a1076cf4b253"

[extensions]
TTITensorConversion = ["ITensors", "ITensorMPS"]
TTT4AITensorCompatConversion = ["ITensors", "T4AITensorCompat"]

[compat]
T4AMatrixCI = "0.1"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[targets]
test = ["Test", "Aqua", "JET", "Random"]
